-- Click ID 발급용 sequence
CREATE SEQUENCE deeplink_click_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 광고앱(app_type)별 분기 설정 테이블
CREATE TABLE dl_app_config (
    provider        VARCHAR2(50) PRIMARY KEY,
    app_name        VARCHAR2(100) NOT NULL,
    app_icon_url    CLOB,
    android_scheme  VARCHAR2(255) NOT NULL,
    ios_scheme      VARCHAR2(255) NOT NULL,
    play_store_url  VARCHAR2(500) NOT NULL,
    app_store_url   VARCHAR2(500) NOT NULL
);
-- 클릭 정보(광고 클릭 -> 서버에서 crypt 발급 시 저장)
CREATE TABLE dl_click_referrer (
    click_id      VARCHAR2(30) PRIMARY KEY,
    provider      VARCHAR2(50) NOT NULL,
    campaign_id   VARCHAR2(100) NOT NULL,
    os            VARCHAR2(20) NOT NULL,
    client_ip     VARCHAR2(50),
    user_agent    CLOB,
    crypt         CLOB NOT NULL,
    payload_json  CLOB,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_click_crypt ON dl_click_referrer (crypt);

-- 랜딩 접근 / 최초 실행 검증 로그
CREATE TABLE dl_access_log (
    access_seq     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    click_id       VARCHAR2(30),
    crypt          CLOB NOT NULL,
    platform       VARCHAR2(20),
    user_pin           VARCHAR2(100),
    verified_yn    CHAR(1) DEFAULT 'N',
    landing_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    first_open_at  TIMESTAMP,
    CONSTRAINT fk_access_click
        FOREIGN KEY (click_id) REFERENCES dl_click_referrer(click_id)
);

